import type { LocalePref } from "..";

export const ja = {
  language: "言語",
  languageLabel: "表示言語",
  localePref: {
    system: "システムに合わせる",
    ja: "日本語",
    en: "English",
  } satisfies Record<LocalePref, string>,
  languageHint: "画面の表示と、AI が生成する文章の言語が切り替わります。",
};

export const en: typeof ja = {
  language: "Language",
  languageLabel: "Display language",
  localePref: {
    system: "Match system",
    ja: "日本語",
    en: "English",
  },
  languageHint: "Changes the language of the interface and of text generated by AI.",
};
