import type { LocalePref } from "..";
import type { ClaudeCodeModel } from "../../lib/ai";
import type { KeyColor, ThemeId, ThemeScheme } from "../../lib/theme";

export const ja = {
  language: "言語",
  languageLabel: "表示言語",
  localePref: {
    system: "システムに合わせる",
    ja: "日本語",
    en: "English",
  } satisfies Record<LocalePref, string>,
  languageHint: "画面の表示と、AI が生成する文章の言語が切り替わります。",

  title: "設定",
  categoriesLabel: "設定のカテゴリ",
  categories: {
    general: "一般",
    style: "スタイル",
    ai: "AI",
  },
  // 一般
  autoFetch: "自動フェッチ",
  autoFetchInterval: "間隔",
  autoFetchOption: (minutes: number) => (minutes === 0 ? "オフ" : `${minutes} 分ごと`),
  autoFetchHint: "開いているリポジトリを裏で git fetch し、変化があれば表示を更新します。",
  projectRoots: "プロジェクトの場所",
  projectRootsDesc:
    "ここに登録したフォルダの配下から git リポジトリを探します。 タブの「+」を押すと、見つかったリポジトリを検索して開けます。",
  remove: "削除",
  noProjectRoots: "まだ登録されていません",
  addFolder: "フォルダを追加",
  rescan: "再検索",
  scanDepth: "探索する階層の深さ",
  scanDepthOption: (depth: number) => `${depth} 階層`,
  scanDepthHint: "深くするほど見つかりますが検索に時間がかかります。",
  scanning: "検索中...",
  reposFound: (n: number) => `現在 ${n} 件のリポジトリを認識しています。`,
  // スタイル
  theme: "テーマ",
  themeLabel: "配色",
  themePref: {
    system: "システムに合わせる（ダーク / ライト）",
    // グループ名 (themeGroup) でダーク / ライトが分かるので、項目名は「標準」だけにする
    dark: "標準",
    light: "標準",
    nord: "Nord",
    dracula: "Dracula",
    solarized: "Solarized Light",
  } satisfies Record<"system" | ThemeId, string>,
  themeGroup: {
    dark: "ダーク",
    light: "ライト",
  } satisfies Record<ThemeScheme, string>,
  themeGroupCustom: "カスタム",
  newTheme: "新しいテーマ",
  editTheme: "編集",
  deleteTheme: "削除",
  saveTheme: "保存",
  cancelTheme: "キャンセル",
  customThemeName: "テーマ名",
  customThemeDefaultName: "マイテーマ",
  customThemeNameMissing: "テーマ名を入力してください。",
  keyColors: {
    bg: "背景",
    fg: "文字",
    accent: "アクセント",
    green: "成功・追加",
    red: "エラー・削除",
    amber: "警告",
    violet: "補助",
  } satisfies Record<KeyColor, string>,
  customThemeDesc:
    "テーマ名とキーカラー 7 色を決めると、残りの色はそこから自動で作ります。編集中の色は画面にそのまま反映されます。",
  customThemeScheme: (scheme: ThemeScheme) =>
    `背景の明るさから${scheme === "light" ? "ライト" : "ダーク"}系のテーマとして扱います。`,
  customThemeLowContrast: (names: string) =>
    `${names} は背景とのコントラストが 4.5:1 に届かず、文字が読みにくいかもしれません。`,
  aiPalette: "パレットから割り当て",
  aiPalettePlaceholder: "#264653 #2a9d8f #e9c46a … を 7 色",
  aiPaletteHint: (count: number) =>
    count === 7
      ? "7 色を背景・文字・アクセントなどのどこに使うか、Claude Code に決めてもらいます。"
      : `色を 7 つ貼り付けてください (いま ${count} 色)。coolors などの URL もそのまま使えます。`,
  aiAssign: "AI で割り当て",
  aiAssigning: "割り当て中…",
  aiAssignFailed: "色を割り当てられませんでした",
  deleteThemeTitle: "テーマを削除",
  deleteThemeMessage: (name: string) => `「${name}」を削除しますか？`,
  themeHint:
    "画面全体の配色を切り替えます。ライト系のテーマでは、差分のシンタックスハイライトも明るい配色で表示します。",
  commitGraph: "コミットグラフ",
  graphStyle: "スタイル",
  graphStyleDefault: "標準（従来のスタイル）",
  graphStyleRailway: "日本の鉄道路線図風",
  graphStyleHint:
    "太い路線と、線幅に近い大きさの駅の◯で表示します。 ノードの表示は、どちらのスタイルでもアバターと◯から選べます。",
  graphNode: "ノードの表示",
  graphNodeAvatar: "アバター",
  diffDisplay: "差分の表示",
  syntaxHighlight: "シンタックスハイライト",
  syntaxHighlightHint:
    "ファイルの拡張子から言語を判定して色を付けます。テーマは選んだものだけを読み込みます。",
  authorAvatars: "作者アイコン",
  authorAvatarsDesc:
    "コミット作者のメールアドレスから gh CLI で GitHub のアバターを引いて表示します。 結果はディスクに残るので、同じ作者を何度も取りに行くことはありません。 アイコンを変えた人が古いままのときだけ、ここで消してください。",
  clearAvatarCache: "キャッシュを消して取り直す",
  // AI
  aiCommitMessage: "AI コミットメッセージ",
  aiCommitMessageDesc:
    "コミット欄の「AI で生成」ボタンで、インストール済みの Claude Code (claude コマンド) に差分からメッセージを作らせます。Claude のサブスクリプションでログインしていれば、 キーの登録は不要です。生成時には差分が Anthropic に送られます。",
  model: "モデル",
  models: {
    sonnet: "Sonnet（最新・バランス）",
    opus: "Opus（最新・高品質）",
    haiku: "Haiku（最新・高速）",
  } satisfies Record<ClaudeCodeModel, string>,
};

export const en: typeof ja = {
  language: "Language",
  languageLabel: "Display language",
  localePref: {
    system: "Match system",
    ja: "日本語",
    en: "English",
  },
  languageHint: "Changes the language of the interface and of text generated by AI.",

  title: "Settings",
  categoriesLabel: "Settings categories",
  categories: {
    general: "General",
    style: "Style",
    ai: "AI",
  },
  autoFetch: "Auto Fetch",
  autoFetchInterval: "Interval",
  autoFetchOption: (minutes) =>
    minutes === 0 ? "Off" : `Every ${minutes} ${minutes === 1 ? "minute" : "minutes"}`,
  autoFetchHint:
    "Runs git fetch on open repositories in the background and updates the view when something changes.",
  projectRoots: "Project Locations",
  projectRootsDesc:
    "git-squid looks for git repositories under the folders listed here. Press “+” on the tab bar to search and open the repositories it finds.",
  remove: "Remove",
  noProjectRoots: "No folders added yet",
  addFolder: "Add Folder",
  rescan: "Rescan",
  scanDepth: "Search depth",
  scanDepthOption: (depth) => `${depth} ${depth === 1 ? "level" : "levels"}`,
  scanDepthHint: "Deeper searches find more repositories but take longer.",
  scanning: "Searching...",
  reposFound: (n) => `${n} ${n === 1 ? "repository" : "repositories"} found.`,
  theme: "Theme",
  themeLabel: "Colors",
  themePref: {
    system: "Match system (Dark / Light)",
    dark: "Standard",
    light: "Standard",
    nord: "Nord",
    dracula: "Dracula",
    solarized: "Solarized Light",
  },
  themeGroup: {
    dark: "Dark",
    light: "Light",
  },
  themeGroupCustom: "Custom",
  newTheme: "New Theme",
  editTheme: "Edit",
  deleteTheme: "Delete",
  saveTheme: "Save",
  cancelTheme: "Cancel",
  customThemeName: "Theme name",
  customThemeDefaultName: "My Theme",
  customThemeNameMissing: "Enter a theme name.",
  keyColors: {
    bg: "Background",
    fg: "Text",
    accent: "Accent",
    green: "Success / Added",
    red: "Error / Deleted",
    amber: "Warning",
    violet: "Secondary",
  },
  customThemeDesc:
    "Pick a name and 7 key colors; the remaining colors are derived from them. Changes are previewed live while editing.",
  customThemeScheme: (scheme) =>
    `Treated as a ${scheme === "light" ? "light" : "dark"} theme based on the background brightness.`,
  customThemeLowContrast: (names) =>
    `${names} ${names.includes(",") ? "have" : "has"} less than 4.5:1 contrast against the background and may be hard to read.`,
  aiPalette: "Assign from palette",
  aiPalettePlaceholder: "7 colors, e.g. #264653 #2a9d8f #e9c46a …",
  aiPaletteHint: (count) =>
    count === 7
      ? "Claude Code decides which of the 7 colors to use for the background, text, accent and so on."
      : `Paste 7 colors (${count} so far). URLs from palette sites such as coolors work too.`,
  aiAssign: "Assign with AI",
  aiAssigning: "Assigning…",
  aiAssignFailed: "Couldn't assign the colors",
  deleteThemeTitle: "Delete Theme",
  deleteThemeMessage: (name) => `Delete "${name}"?`,
  themeHint:
    "Changes the colors of the whole app. With a light theme, diff syntax highlighting also uses a light palette.",
  commitGraph: "Commit Graph",
  graphStyle: "Style",
  graphStyleDefault: "Standard (classic style)",
  graphStyleRailway: "Japanese railway map style",
  graphStyleHint:
    "Draws thick lines with station circles close to the line width. Either style can show nodes as avatars or circles.",
  graphNode: "Nodes",
  graphNodeAvatar: "Avatar",
  diffDisplay: "Diffs",
  syntaxHighlight: "Syntax highlighting",
  syntaxHighlightHint:
    "Colors code based on the file extension. Only the selected theme is loaded.",
  authorAvatars: "Author Avatars",
  authorAvatarsDesc:
    "Looks up GitHub avatars from commit author emails via the gh CLI. Results are cached on disk, so the same author is never fetched twice. Clear the cache only when someone's changed avatar still shows the old one.",
  clearAvatarCache: "Clear Cache and Refetch",
  aiCommitMessage: "AI Commit Messages",
  aiCommitMessageDesc:
    "The “Generate with AI” button in the commit box asks your installed Claude Code (the claude command) to write a message from the diff. If you're signed in with a Claude subscription, no API key is needed. The diff is sent to Anthropic when generating.",
  model: "Model",
  models: {
    sonnet: "Sonnet (latest, balanced)",
    opus: "Opus (latest, highest quality)",
    haiku: "Haiku (latest, fastest)",
  },
};
